services:
  frontend:
    build: ./tunefy-main/frontend
    ports:
      - 80:3000
    #depends_on:
  #    - backend
    networks:
      - febe
    env_file:
      - .env
    
      
  backend:
    build: ./tunefy-main/backend
    ports:
      - 3001:3001
  #  depends_on:
   #   - database
    networks:
      - febe
      - bedb
    env_file:
      - .env


  database:
    build: ./tunefy-main/database
    ports:
      - 5432:5432
    networks:
      - bedb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


networks:
  febe:
    driver: bridge
  bedb:
    driver: bridge

