services:
  frontend:
    build: ./tunefy-main/frontend
    ports:
      - 80:3000
    networks:
      - febe
    env_file:
      - ./tunefy-main/frontend/.env
    
      
  backend:
    build: ./tunefy-main/backend
    ports:
      - 3001:3001
    networks:
      - febe
      - bedb
    env_file:
      - ./tunefy-main/backend/.env


  database:
    build: ./tunefy-main/database
    ports:
      - 5432:5432
    networks:
      - bedb
    env_file:
      - ./tunefy-main/database/.env
      

networks:
  febe:
    driver: bridge
  bedb:
    driver: bridge

